version: 2.1

jobs:
  build:
    docker:
      - image: 'rust:1.34-stretch'
    steps:
      - 'checkout'
      - run: 'apt-get update'
      - run: 'apt-get install -y time'
      - run: '/usr/bin/time cargo build --release --locked -vv'
      - run: 'cargo clean'
      - run: 'MAKE_LIBSASS_JOBS=4 /usr/bin/time cargo build --release --locked -vv'
